version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    hostname: cassandra-node1
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraDemoCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - ./configs/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - cassandra-data1:/var/lib/cassandra
    networks:
      - cassandra-network

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    hostname: cassandra-node2
    ports:
      - "9043:9042"
      - "7002:7000"
      - "7003:7001"
      - "9161:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraDemoCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - ./configs/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - cassandra-data2:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node1

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    hostname: cassandra-node3
    ports:
      - "9044:9042"
      - "7004:7000"
      - "7005:7001"
      - "9162:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraDemoCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - ./configs/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - cassandra-data3:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node1

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:

networks:
  cassandra-network:
    driver: bridge
